### ISSUE TITLE
Cant add points to players

### ISSUE THREAD

**Issue by EinEisbxr** [TechnikAG-HHG/footballtree#108]
Game is set up like this:
1. team 1 - 10
2. in each team: player 1 - 10

And I cant add any points to players, error:

Traceback (most recent call last):
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\GitHub\footballtree\code\main.py", line 1076, in <lambda>
    playerbutton2 = ctk.CTkButton(self.group_frame, text="DOWN", command=lambda team=team_id, player_id1=player_id, player_index = player_index: self.player_scored_a_point(team, player_id1, player_index, "DOWN"), fg_color="#34757a", hover_color="#1f4346", font=("Helvetica", self.team_button_font_size), height=self.team_button_height, width=self.team_button_width)
                                                                                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\GitHub\footballtree\code\main.py", line 1224, in player_scored_a_point
    current_goals = self.read_player_stats(teamID, True, player_id)[0][2]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by Limonadeundco** [comment]
![grafik](https://github.com/TechnikAG-HHG/footballtree/assets/117310683/b57e0638-5311-4d44-8c79-da9537b96c44)

Cant recreate, please test on the newest version again!

**Comment by EinEisbxr** [comment]
cant recreate it at the moment either
