### ISSUE TITLE
Possible bug when there are no matches (no teams) and you try to select the active match site

### ISSUE THREAD

**Issue by Limonadeundco** [TechnikAG-HHG/footballtree#160]

**Comment by EinEisbxr** [comment]
Error message:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1962, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python312\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\GitHub\footballtree\code\main.py", line 2385, in show_SPIEL_frame
    self.reload_spiel_button_command()
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\GitHub\footballtree\code\main.py", line 1472, in reload_spiel_button_command
    self.create_SPIEL_elements()
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\GitHub\footballtree\code\main.py", line 1019, in create_SPIEL_elements
    team_name = team_names[self.teams_playing[i]]
                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

**Comment by EinEisbxr** [comment]
fixed it
