### ISSUE TITLE
Database Locked Exeption on tip submit 

### ISSUE THREAD

**Issue by Limonadeundco** [TechnikAG-HHG/footballtree#294]
/home/codespace/.python/current/bin/python3 /workspaces/footballtree/code/main.py
@Limonadeundco ➜ /workspaces/footballtree (Implementation-of-KO-mode) $ /home/codespace/.python/current/bin/python3 /workspaces/footballtree/code/main.py
 * Serving Flask app 'main'
 * Debug mode: off
Forwarding HTTP traffic from https://technikag.serveo.net
HTTP request from 87.175.121.99 to https://technikag.serveo.net/
HTTP request from 87.175.121.99 to https://technikag.serveo.net/site.webmanifest
HTTP request from 87.175.121.99 to https://technikag.serveo.net/static/websitemain.css
HTTP request from 87.175.121.99 to https://technikag.serveo.net/static/websitemain.js
HTTP request from 87.175.121.99 to https://technikag.serveo.net/update_data
HTTP request from 87.175.121.99 to https://technikag.serveo.net/plan
HTTP request from 87.175.121.99 to https://technikag.serveo.net/site.webmanifest
HTTP request from 87.175.121.99 to https://technikag.serveo.net/static/websiteplan.js
HTTP request from 87.175.121.99 to https://technikag.serveo.net/static/websiteplan.css
HTTP request from 87.175.121.99 to https://technikag.serveo.net/update_data
HTTP request from 87.175.121.99 to https://technikag.serveo.net/
HTTP request from 87.175.121.99 to https://technikag.serveo.net/site.webmanifest
HTTP request from 87.175.121.99 to https://technikag.serveo.net/static/websitemain.css
HTTP request from 87.175.121.99 to https://technikag.serveo.net/static/websitemain.js
HTTP request from 87.175.121.99 to https://technikag.serveo.net/update_data
HTTP request from 87.175.121.99 to https://technikag.serveo.net/group
HTTP request from 87.175.121.99 to https://technikag.serveo.net/site.webmanifest
HTTP request from 87.175.121.99 to https://technikag.serveo.net/static/websitegroup.css
HTTP request from 87.175.121.99 to https://technikag.serveo.net/static/websitegroup.js
HTTP request from 87.175.121.99 to https://technikag.serveo.net/update_data
HTTP request from 87.175.121.99 to https://technikag.serveo.net/
HTTP request from 87.175.121.99 to https://technikag.serveo.net/static/websitemain.css
HTTP request from 87.175.121.99 to https://technikag.serveo.net/site.webmanifest
HTTP request from 87.175.121.99 to https://technikag.serveo.net/static/websitemain.js
HTTP request from 87.175.121.99 to https://technikag.serveo.net/update_data
HTTP request from 87.175.121.99 to https://technikag.serveo.net/tree
HTTP request from 87.175.121.99 to https://technikag.serveo.net/site.webmanifest
HTTP request from 87.175.121.99 to https://technikag.serveo.net/static/websitetree.css
HTTP request from 87.175.121.99 to https://technikag.serveo.net/static/websitetree.js
HTTP request from 87.175.121.99 to https://technikag.serveo.net/
HTTP request from 87.175.121.99 to https://technikag.serveo.net/site.webmanifest
HTTP request from 87.175.121.99 to https://technikag.serveo.net/static/websitemain.css
HTTP request from 87.175.121.99 to https://technikag.serveo.net/static/websitemain.js
HTTP request from 87.175.121.99 to https://technikag.serveo.net/update_data
HTTP request from 87.175.121.99 to https://technikag.serveo.net/tipping
HTTP request from 87.175.121.99 to https://technikag.serveo.net/login
HTTP request from 87.175.121.99 to https://technikag.serveo.net/callback?state=Akojr3xLYk5tDpV9lH1VKAlsc9WCV4&code=4%2F0AeaYSHDYwJFkGEYyb8zsJxd46v68dQ3h51V5wml-ClmNR9osxymcfChXUijQaBSuBlzZRA&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile&authuser=0&prompt=none
HTTP request from 87.175.121.99 to http://technikag.serveo.net/tipping
HTTP request from 87.175.121.99 to http://technikag.serveo.net/static/websitetipping.css
HTTP request from 87.175.121.99 to http://technikag.serveo.net/static/websitetipping.js
HTTP request from 87.175.121.99 to http://technikag.serveo.net/tipping_data
HTTP request from 87.175.121.99 to http://technikag.serveo.net/update_data
HTTP request from 87.175.121.99 to http://technikag.serveo.net/tipping_data
HTTP request from 87.175.121.99 to http://technikag.serveo.net/update_data
HTTP request from 87.175.121.99 to http://technikag.serveo.net/tipping_data
HTTP request from 87.175.121.99 to http://technikag.serveo.net/update_data
HTTP request from 87.175.121.99 to http://technikag.serveo.net/tipping_data
HTTP request from 87.175.121.99 to http://technikag.serveo.net/update_data
HTTP request from 87.175.121.99 to http://technikag.serveo.net/send_tipping_data
HTTP request from 87.175.121.99 to http://technikag.serveo.net/send_tipping_data
HTTP request from 87.175.121.99 to http://technikag.serveo.net/tipping_data
HTTP request from 87.175.121.99 to http://technikag.serveo.net/update_data
HTTP request from 87.175.121.99 to http://technikag.serveo.net/send_tipping_data
HTTP request from 87.175.121.99 to http://technikag.serveo.net/send_tipping_data
HTTP request from 87.175.121.99 to http://technikag.serveo.net/send_tipping_data
HTTP request from 87.175.121.99 to http://technikag.serveo.net/send_tipping_data
2024-03-07 07:04:16,261 - ERROR - Exception on /send_tipping_data [POST]
                                                                        Traceback (most recent call last):
                                                                                                            File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
                                                                                          response = self.full_dispatch_request()
     File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
                                                                                                                             rv = self.handle_user_exception(e)
                                   File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
                             rv = self.dispatch_request()
                                                           File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
                                                return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
                           File "/workspaces/footballtree/code/main.py", line 3552, in decorator
                                                                                                    return function(*args, **kwargs)
        File "/workspaces/footballtree/code/main.py", line 3682, in send_tipping_data
                                                                                         cursor.execute("INSERT INTO tippingData (googleId, matchId, team1Goals, team2Goals) VALUES (?, ?, ?, ?)", (google_id, match_id, team1_goals, team2_goals))
                                                                                                                     sqlite3.OperationalError: database is locked
                                   2024-03-07 07:04:17,478 - ERROR - Exception on /send_tipping_data [POST]
                                                                                                           Traceback (most recent call last):
                 File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
                                                                                                                             response = self.full_dispatch_request()
                                        File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
                                  rv = self.handle_user_exception(e)
                                                                      File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
                                                                rv = self.dispatch_request()
                                                                                              File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
                                                                                   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
                                                              File "/workspaces/footballtree/code/main.py", line 3552, in decorator
         return function(*args, **kwargs)
                                           File "/workspaces/footballtree/code/main.py", line 3682, in send_tipping_data
                                                                                                                            cursor.execute("INSERT INTO tippingData (googleId, matchId, team1Goals, team2Goals) VALUES (?, ?, ?, ?)", (google_id, match_id, team1_goals, team2_goals))
                          sqlite3.OperationalError: database is locked
                                                                      HTTP request from 87.175.121.99 to http://technikag.serveo.net/tipping_data
HTTP request from 87.175.121.99 to http://technikag.serveo.net/update_data
2024-03-07 07:04:18,217 - ERROR - Exception on /send_tipping_data [POST]
                                                                        Traceback (most recent call last):
                                                                                                            File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
                                                                                          response = self.full_dispatch_request()
     File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
                                                                                                                             rv = self.handle_user_exception(e)
                                   File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
                             rv = self.dispatch_request()
                                                           File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
                                                return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
                           File "/workspaces/footballtree/code/main.py", line 3552, in decorator
                                                                                                    return function(*args, **kwargs)
        File "/workspaces/footballtree/code/main.py", line 3682, in send_tipping_data
                                                                                         cursor.execute("INSERT INTO tippingData (googleId, matchId, team1Goals, team2Goals) VALUES (?, ?, ?, ?)", (google_id, match_id, team1_goals, team2_goals))
                                                                                                                     sqlite3.OperationalError: database is locked
                                   2024-03-07 07:04:18,939 - ERROR - Exception on /send_tipping_data [POST]
                                                                                                           Traceback (most recent call last):
                 File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
                                                                                                                             response = self.full_dispatch_request()
                                        File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
                                  rv = self.handle_user_exception(e)
                                                                      File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
                                                                rv = self.dispatch_request()
                                                                                              File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
                                                                                   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
                                                              File "/workspaces/footballtree/code/main.py", line 3552, in decorator
         return function(*args, **kwargs)
                                           File "/workspaces/footballtree/code/main.py", line 3682, in send_tipping_data
                                                                                                                            cursor.execute("INSERT INTO tippingData (googleId, matchId, team1Goals, team2Goals) VALUES (?, ?, ?, ?)", (google_id, match_id, team1_goals, team2_goals))
                          sqlite3.OperationalError: database is locked
                                                                      HTTP request from 87.175.121.99 to http://technikag.serveo.net/send_tipping_data
2024-03-07 07:04:19,371 - ERROR - Exception on /send_tipping_data [POST]
                                                                        Traceback (most recent call last):
                                                                                                            File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
                                                                                          response = self.full_dispatch_request()
     File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
                                                                                                                             rv = self.handle_user_exception(e)
                                   File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
                             rv = self.dispatch_request()
                                                           File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
                                                return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
                           File "/workspaces/footballtree/code/main.py", line 3552, in decorator
                                                                                                    return function(*args, **kwargs)
        File "/workspaces/footballtree/code/main.py", line 3682, in send_tipping_data
                                                                                         cursor.execute("INSERT INTO tippingData (googleId, matchId, team1Goals, team2Goals) VALUES (?, ?, ?, ?)", (google_id, match_id, team1_goals, team2_goals))
                                                                                                                     sqlite3.OperationalError: database is locked
                                   HTTP request from 87.175.121.99 to http://technikag.serveo.net/send_tipping_data
HTTP request from 87.175.121.99 to http://technikag.serveo.net/send_tipping_data
HTTP request from 87.175.121.99 to http://technikag.serveo.net/send_tipping_data
2024-03-07 07:04:20,519 - ERROR - Exception on /send_tipping_data [POST]
                                                                        Traceback (most recent call last):
                                                                                                            File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
                                                                                          response = self.full_dispatch_request()
     File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
                                                                                                                             rv = self.handle_user_exception(e)
                                   File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
                             rv = self.dispatch_request()
                                                           File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
                                                return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
                           File "/workspaces/footballtree/code/main.py", line 3552, in decorator
                                                                                                    return function(*args, **kwargs)
        File "/workspaces/footballtree/code/main.py", line 3682, in send_tipping_data
                                                                                         cursor.execute("INSERT INTO tippingData (googleId, matchId, team1Goals, team2Goals) VALUES (?, ?, ?, ?)", (google_id, match_id, team1_goals, team2_goals))
                                                                                                                     sqlite3.OperationalError: database is locked
                                   HTTP request from 87.175.121.99 to http://technikag.serveo.net/send_tipping_data
HTTP request from 87.175.121.99 to http://technikag.serveo.net/update_data
HTTP request from 87.175.121.99 to http://technikag.serveo.net/tipping_data
2024-03-07 07:04:24,283 - ERROR - Exception on /send_tipping_data [POST]
                                                                        Traceback (most recent call last):
                                                                                                            File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
                                                                                          response = self.full_dispatch_request()
     File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
                                                                                                                             rv = self.handle_user_exception(e)
                                   File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
                             rv = self.dispatch_request()
                                                           File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
                                                return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
                           File "/workspaces/footballtree/code/main.py", line 3552, in decorator
                                                                                                    return function(*args, **kwargs)
        File "/workspaces/footballtree/code/main.py", line 3682, in send_tipping_data
                                                                                         cursor.execute("INSERT INTO tippingData (googleId, matchId, team1Goals, team2Goals) VALUES (?, ?, ?, ?)", (google_id, match_id, team1_goals, team2_goals))
                                                                                                                     sqlite3.OperationalError: database is locked
                                   2024-03-07 07:04:25,023 - ERROR - Exception on /send_tipping_data [POST]
                                                                                                           Traceback (most recent call last):
                 File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
                                                                                                                             response = self.full_dispatch_request()
                                        File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
                                  rv = self.handle_user_exception(e)
                                                                      File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
                                                                rv = self.dispatch_request()
                                                                                              File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
                                                                                   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
                                                              File "/workspaces/footballtree/code/main.py", line 3552, in decorator
         return function(*args, **kwargs)
                                           File "/workspaces/footballtree/code/main.py", line 3682, in send_tipping_data
                                                                                                                            cursor.execute("INSERT INTO tippingData (googleId, matchId, team1Goals, team2Goals) VALUES (?, ?, ?, ?)", (google_id, match_id, team1_goals, team2_goals))
                          sqlite3.OperationalError: database is locked
                                                                      2024-03-07 07:04:25,244 - ERROR - Exception on /send_tipping_data [POST]
                Traceback (most recent call last):
                                                    File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
                                  response = self.full_dispatch_request()
                                                                           File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
                                                                     rv = self.handle_user_exception(e)
                                                                                                         File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
                                                                                                   rv = self.dispatch_request()
   File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
                                                                                                                      return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
                                                                                                 File "/workspaces/footballtree/code/main.py", line 3552, in decorator
                                            return function(*args, **kwargs)
                                                                              File "/workspaces/footballtree/code/main.py", line 3682, in send_tipping_data
                                 cursor.execute("INSERT INTO tippingData (googleId, matchId, team1Goals, team2Goals) VALUES (?, ?, ?, ?)", (google_id, match_id, team1_goals, team2_goals))
                                                             sqlite3.OperationalError: database is locked
                                                                                                         2024-03-07 07:04:25,453 - ERROR - Exception on /send_tipping_data [POST]
                                                   Traceback (most recent call last):
                                                                                       File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
                                                                     response = self.full_dispatch_request()
                                                                                                              File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
                                                                                                        rv = self.handle_user_exception(e)
              File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
        rv = self.dispatch_request()
                                      File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
                           return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
      File "/workspaces/footballtree/code/main.py", line 3552, in decorator
                                                                               return function(*args, **kwargs)
                                                                                                                 File "/workspaces/footballtree/code/main.py", line 3682, in send_tipping_data
                                                                    cursor.execute("INSERT INTO tippingData (googleId, matchId, team1Goals, team2Goals) VALUES (?, ?, ?, ?)", (google_id, match_id, team1_goals, team2_goals))
                                                                                                sqlite3.OperationalError: database is locked
              2024-03-07 07:04:25,653 - ERROR - Exception on /send_tipping_data [POST]
                                                                                      Traceback (most recent call last):
                                                                                                                          File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
                                                                                                        response = self.full_dispatch_request()
                   File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
             rv = self.handle_user_exception(e)
                                                 File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
                                           rv = self.dispatch_request()
                                                                         File "/home/codespace/.python/current/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
                                                              return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
                                         File "/workspaces/footballtree/code/main.py", line 3552, in decorator
                                                                                                                  return function(*args, **kwargs)
                      File "/workspaces/footballtree/code/main.py", line 3682, in send_tipping_data
                                                                                                       cursor.execute("INSERT INTO tippingData (googleId, matchId, team1Goals, team2Goals) VALUES (?, ?, ?, ?)", (google_id, match_id, team1_goals, team2_goals))
     sqlite3.OperationalError: database is locked
                                                 HTTP request from 87.175.121.99 to http://technikag.serveo.net/tipping_data

**Comment by Limonadeundco** [comment]
Only on Linux
