### ISSUE TITLE
Internal server Error in final phase

### ISSUE THREAD

**Issue by EinEisbxr** [TechnikAG-HHG/footballtree#79]
After selecting final phase and reloading:

[2023-12-16 21:03:54,898] ERROR in app: Exception on /plan [GET]
Traceback (most recent call last):
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request 
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request 
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request      
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\GitHub\footballtree\code\main.py", line 2578, in plan_index
    return get_initial_data("websiteplan.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\GitHub\footballtree\code\main.py", line 2556, in get_initial_data    
    "finalMatches": get_data_for_website(6),
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\GitHub\footballtree\code\main.py", line 2496, in get_data_for_website
    final_goles.append([ich_kann_nicht_mehr(tkapp.endteam1[0], tkapp.endteam3[0]), ich_kann_nicht_mehr(tkapp.endteam3[0], tkapp.endteam1[0])])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\GitHub\footballtree\code\main.py", line 2529, in ich_kann_nicht_mehr 
    team1_or_team2 = onefetched[0]
                     ~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
192.168.178.56 - - [16/Dec/2023 21:03:54] "GET /plan HTTP/1.1" 500 -
[2023-12-16 21:03:55,872] ERROR in app: Exception on /plan [GET]
Traceback (most recent call last):
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request 
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request 
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request      
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\GitHub\footballtree\code\main.py", line 2578, in plan_index
    return get_initial_data("websiteplan.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\GitHub\footballtree\code\main.py", line 2556, in get_initial_data    
    "finalMatches": get_data_for_website(6),
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\GitHub\footballtree\code\main.py", line 2496, in get_data_for_website
    final_goles.append([ich_kann_nicht_mehr(tkapp.endteam1[0], tkapp.endteam3[0]), ich_kann_nicht_mehr(tkapp.endteam3[0], tkapp.endteam1[0])])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\GitHub\footballtree\code\main.py", line 2529, in ich_kann_nicht_mehr 
    team1_or_team2 = onefetched[0]
                     ~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
192.168.178.56 - - [16/Dec/2023 21:03:55] "GET /plan HTTP/1.1" 500 -
[2023-12-16 21:03:56,207] ERROR in app: Exception on /plan [GET]
Traceback (most recent call last):
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request 
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request 
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request      
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\GitHub\footballtree\code\main.py", line 2578, in plan_index
    return get_initial_data("websiteplan.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\GitHub\footballtree\code\main.py", line 2556, in get_initial_data    
    "finalMatches": get_data_for_website(6),
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\GitHub\footballtree\code\main.py", line 2496, in get_data_for_website
    final_goles.append([ich_kann_nicht_mehr(tkapp.endteam1[0], tkapp.endteam3[0]), ich_kann_nicht_mehr(tkapp.endteam3[0], tkapp.endteam1[0])])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\GitHub\footballtree\code\main.py", line 2529, in ich_kann_nicht_mehr 
    team1_or_team2 = onefetched[0]
                     ~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by Limonadeundco** [comment]
I did not encounter this issue
