### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by EinEisbxr** [TechnikAG-HHG/footballtree#91]
How to recreate:
1. delete database
2. add 8 teams
3. dont go to matches page, start the final phase instantly
4. load plan website

Error:
[2024-02-22 18:10:04,893] ERROR in app: Exception on /plan [GET]
Traceback (most recent call last):
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Felix\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\Github\footballtree\code\main.py", line 2647, in plan_index
    return get_initial_data("websiteplan.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\Github\footballtree\code\main.py", line 2623, in get_initial_data
    "finalMatches": get_data_for_website(6),
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\Github\footballtree\code\main.py", line 2562, in get_data_for_website
    final_goles.append([ich_kann_nicht_mehr(tkapp.endteam1[0], tkapp.endteam3[0]), ich_kann_nicht_mehr(tkapp.endteam3[0], tkapp.endteam1[0])])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Felix\OneDrive - Helmholtz-Gymnasium\Desktop\Github\footballtree\code\main.py", line 2596, in ich_kann_nicht_mehr
    team1_or_team2 = onefetched[0]
                     ~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
192.168.178.56 - - [22/Feb/2024 18:10:04] "GET /plan HTTP/1.1" 500 -

**Comment by EinEisbxr** [comment]
If final teams have never been created, this error happens, after creating the final teams it is fixed

**Comment by Limonadeundco** [comment]
tried to fix it, download the new update when its avaliable on steam and leave a like here!
